-- Per-step pipeline timing (milliseconds)
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS crawl_ms INT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS perf_ms INT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS a11y_ms INT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS seo_ms INT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS report_ms INT;
